CREATE TABLE Fornecedor (
  ID[ INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Fornecedor VARCHAR(100) NULL,
  PRIMARY KEY(ID[)
);

CREATE TABLE Fornecedor_has_Produto (
  Fornecedor_ID[ INTEGER UNSIGNED NOT NULL,
  Produto_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Fornecedor_ID[, Produto_ID),
  INDEX Fornecedor_has_Produto_FKIndex1(Fornecedor_ID[),
  INDEX Fornecedor_has_Produto_FKIndex2(Produto_ID)
);

CREATE TABLE LOJA (
  iD INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LOJA VARCHAR(100) NULL,
  PREÇO FLOAT NULL,
  PRODUTO_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(iD)
);

CREATE TABLE Produto (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PRODUTO VARCHAR(50) NULL,
  PRIMARY KEY(ID)
);

